# -*- coding: utf-8 -*-
"""MandelbrotPlotter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N54Lizm1w0s8xtQreJi2qsVkXXaTPeso
"""

a_values = np.linspace(-2,1,1500)
b_values = np.linspace(-1,1,1000)
mandelbrot_set = [[],[]]
for a in a_values:
    for b in b_values:
        c = complex(a,b)
        z = 0
        count = 0
        while count <= 500:
            z = (z*z) + c
            count+=1
        if np.absolute(z) < 2:
            mandelbrot_set[0]+=[a]
            mandelbrot_set[1]+=[b]
plt.scatter(mandelbrot_set[0], mandelbrot_set[1], s=1)
plt.title('Mandelbrot Set')
plt.axis('equal')
fig = plt.gcf()
fig.set_size_inches(12,12)
plt.show()

